using BEntities.Filters;
using BEntities.SAP;
using System;
using System.Collections.Generic;
using System.Text;
using BEA = BEntities.SAP;

namespace DALayer.SAP
{
    [Serializable()]
    public class StateAccount : Hana.DALEntity<BEA.StateAccountItem>
    {

        #region Methods

        protected override void LoadRelations(ref StateAccountItem Item, params Enum[] Relations) { }

        protected override void LoadRelations(ref IEnumerable<StateAccountItem> Items, params Enum[] Relations) { }

        #endregion

        #region List Methods

        public IEnumerable<BEA.StateAccountItem> List(List<Field> FilterList, string Order)
        {
            var filter = GetFilter(FilterList?.ToArray());
            var sb = new StringBuilder();
            sb.AppendLine($@"SELECT  TA.""Subsidiary"", TA.""Warehouse"", (CASE TA.""Type"" WHEN 'FAC' THEN 'Factura' WHEN 'ND' THEN 'Nota de Débito' WHEN 'PRC' THEN 'Pago Efectuado' WHEN 'PEC' THEN 'Pago' WHEN 'RD' THEN 'Registro Diario' WHEN 'NC' THEN 'Devolucion' END) AS ""Type""  ");
            sb.AppendLine($@"        , TA.""DocNum"", TA.""ClientCode"", TA.""ClientName"", (CASE WHEN TA.""Type"" = 'FAC' THEN TA.""DocNum"" END) AS ""SaleNote"", TA.""SaleOrder"", TA.""Terms"", CAST(TA.""DocDate"" AS DATE) AS ""DocDate"", ""BillSerie"" ");
            sb.AppendLine($@"        , CAST(TA.""DueDate"" AS DATE) AS ""DueDate"", TA.""Total"", TA.""Balance"", TA.""Days"", TA.""Hold"" ");
            sb.AppendLine($@"        , (CASE WHEN (TA.""Type"" = 'FAC' AND TA.""Days"" <= 0) THEN 'Vigente' WHEN (TA.""Type"" = 'FAC' AND TA.""Days"" > 0) THEN 'En Mora' WHEN (TA.""Type"" = 'PRC') THEN 'Abono' END) AS ""State"", TA.""ClientOrder""  ");
            sb.AppendLine($@"        , TA.""TrgetEntry"", TA.""SellerName"", TA.""SellerCode"", ""Header"", ""Footer"", ""Margin"", ""TaxlessToral"", ""PickupDate"", ""IsDeliveryNote""  ");
            sb.AppendLine($@"FROM   ( SELECT  ""Subsidiary"", ""Type"", ""CardCode"" AS ""ClientCode"", ""CardName"" AS ""ClientName"", FIRST_VALUE(""Warehouse"" ORDER BY ""DocNum"") AS ""Warehouse"", ""DocNum"", STRING_AGG(""SaleOrder"", ', ') AS ""SaleOrder"", STRING_AGG(""NumAtCard"", ', ') AS ""ClientOrder"", ""DocDate"", ""Terms"", ""DueDate"", ""Total"" ");
            sb.AppendLine($@"                 , ""Balance"", ""Days"", ""Hold"", ""TrgetEntry"", ""Memo"" AS ""SellerName"", ""SlpName"" AS ""SellerCode"", ""Header"", ""Footer"", SUM(""Margen"") AS ""Margin"", SUM(""TotalCalculo"") AS ""TaxlessToral"", ""PickupDate"", ""IsDeliveryNote"", 0 AS ""BillSerie"" ");
            sb.AppendLine($@"         FROM    ( SELECT  * ");
            sb.AppendLine($@"                   FROM    ( SELECT DISTINCT 'Miami' AS ""Subsidiary"", 'FAC' AS ""Type"", T0.""CardCode"", T3.""CardName"", T4.""WhsName"" AS ""Warehouse"", T0.""DocNum"", T1.""BaseRef"" AS ""SaleOrder"", T5.""NumAtCard"", T0.""DocDate"", T2.""PymntGroup"" AS ""Terms""  ");
            sb.AppendLine($@"                                     , T7.""DueDate"", T7.""InsTotal"" AS ""Total"", (T7.""InsTotal"" - T7.""PaidToDate"") AS ""Balance"", DAYS_BETWEEN(T7.""DueDate"", NOW()) AS ""Days"" ");
            sb.AppendLine($@"                                     , (CASE WHEN ((DAYS_BETWEEN(T7.""DueDate"", NOW()) > 7) AND (T7.""InsTotal"" - T7.""PaidToDate"") > 0) THEN 'HOLD' ELSE ' ' END) AS ""Hold"", T1.""TrgetEntry"", T6.""Memo"", T6.""SlpName"", CAST(T5.""Header"" AS varchar(5000)) AS ""Header""  ");
            sb.AppendLine($@"                                     , CAST(T5.""Footer"" AS varchar(5000)) AS ""Footer"", SUM(T1.""Quantity"" * (T1.""PriceAfVAT"" - T1.""StockPrice"")) AS ""Margen""  ");
            sb.AppendLine($@"                                     , SUM(T1.""Quantity"" * T1.""PriceAfVAT"") AS ""TotalCalculo"", T5.U_FECHAR1 AS ""PickupDate"" ");
            sb.AppendLine($@"                                     , ( CASE FIRST_VALUE(T1.""BaseType"" ORDER BY ""LineNum"") WHEN 15 THEN 'Y' ELSE 'N' END ) AS ""IsDeliveryNote"" ");
            sb.AppendLine($@"                             FROM    {DBLA}.OINV T0  ");
            sb.AppendLine($@"                                     INNER JOIN {DBLA}.INV1 T1 ON T0.""DocEntry"" = T1.""DocEntry"" AND (T0.""DocTotal"" - T0.""PaidToDate"") <> 0  ");
            sb.AppendLine($@"                                     INNER JOIN {DBLA}.OCTG T2 ON T0.""GroupNum"" = T2.""GroupNum""  ");
            sb.AppendLine($@"                                     LEFT OUTER JOIN {DBLA}.OCRD T3 ON T3.""CardCode"" = T0.""CardCode""  ");
            sb.AppendLine($@"                                     LEFT OUTER JOIN {DBLA}.OWHS T4 ON T4.""WhsCode"" = T1.""WhsCode""  ");
            sb.AppendLine($@"                                     LEFT OUTER JOIN {DBLA}.ORDR T5 ON T5.""DocEntry"" = T1.""BaseEntry""  ");
            sb.AppendLine($@"                                     INNER JOIN {DBLA}.OSLP T6 ON T0.""SlpCode"" = T6.""SlpCode""  ");
            sb.AppendLine($@"                                     INNER JOIN {DBLA}.INV6 T7 ON T7.""DocEntry"" = T0.""DocEntry"" ");
            sb.AppendLine($@"                             WHERE	  T0.""DocSubType"" = '--' AND (T7.""InsTotal"" - T7.""PaidToDate"") > 0 ");
            sb.AppendLine($@"                             GROUP BY T0.""CardCode"", T3.""CardName"", ""WhsName"", T0.""DocNum"", ""BaseRef"", T5.""NumAtCard"", T0.""DocDate"", ""PymntGroup"", T7.""DueDate"", T7.""InsTotal"", T7.""PaidToDate"", ""TrgetEntry"", T6.""Memo"", T6.""SlpName""  ");
            sb.AppendLine($@"                                     , CAST(T5.""Header"" AS varchar(5000)), CAST(T5.""Footer"" AS varchar(5000)), T5.U_FECHAR1 ) a ) a1 ");            
            sb.AppendLine($@"         GROUP BY ""Subsidiary"", ""Type"", ""CardCode"", ""CardName"", ""DocNum"", ""DocDate"", ""Terms"", ""DueDate"", ""Total"", ""Balance"", ""Days"", ""Hold"", ""TrgetEntry"", ""Memo"", ""SlpName"", ""Header"", ""Footer"", ""PickupDate"", ""IsDeliveryNote"" ");
            sb.AppendLine($@"        UNION ALL  ");
            sb.AppendLine($@"        SELECT DISTINCT 'Miami' AS ""BD"", 'ND', T0.""CardCode"", T3.""CardName"", T4.""WhsName"" AS ""ALMACEN"", T0.""DocNum"", T1.""BaseRef"", '', T0.""DocDate"", T2.""PymntGroup"", T0.""DocDueDate"", T0.""DocTotal"" AS ""TOTAL""  ");
            sb.AppendLine($@"                , (T0.""DocTotal"" - T0.""PaidToDate"") AS ""Balance"", DAYS_BETWEEN(T0.""DocDueDate"", NOW()) AS ""Days""  ");
            sb.AppendLine($@"                , (CASE WHEN ((DAYS_BETWEEN(T0.""DocDueDate"", NOW()) > 7) AND (T0.""DocTotal"" - T0.""PaidToDate"") > 0) THEN 'HOLD' ELSE '' END) AS ""SITUACION"", T1.""TrgetEntry"", T5.""Memo"", T5.""SlpName"", '' AS ""Header"", '' AS ""Footer""  ");
            sb.AppendLine($@"                , SUM(T1.""Quantity"" * (T1.""PriceAfVAT"" - T1.""StockPrice"")) AS ""Margen"", SUM(T1.""Quantity"" * T1.""PriceAfVAT"") AS ""TotalCalculo"", NULL, 'N', 0  ");
            sb.AppendLine($@"        FROM    {DBLA}.OINV T0  ");
            sb.AppendLine($@"                INNER JOIN {DBLA}.INV1 T1 ON T0.""DocEntry"" = T1.""DocEntry""  ");
            sb.AppendLine($@"                INNER JOIN {DBLA}.OCTG T2 ON T0.""GroupNum"" = T2.""GroupNum""  ");
            sb.AppendLine($@"                LEFT OUTER JOIN {DBLA}.OCRD T3 ON T3.""CardCode"" = T0.""CardCode""  ");
            sb.AppendLine($@"                LEFT OUTER JOIN {DBLA}.OWHS T4 ON T4.""WhsCode"" = T1.""WhsCode""  ");
            sb.AppendLine($@"                INNER JOIN {DBLA}.OSLP T5 ON T0.""SlpCode"" = T5.""SlpCode""  ");
            sb.AppendLine($@"        WHERE   T0.CANCELED = 'N' AND (T0.""CardCode"" <> 'CIMP-008' AND T0.""CardCode"" <> 'CDMC-002') AND (T1.""TargetType"" <> 14 OR T1.""TargetType"" IS NULL) AND T0.""DocSubType"" = 'DN' AND (T0.""DocTotal"" - T0.""PaidToDate"") <> 0  ");
            sb.AppendLine($@"        GROUP BY T0.""CardCode"", T3.""CardName"", ""WhsName"", T0.""DocNum"", ""BaseRef"", T0.""DocDate"", ""PymntGroup"", T0.""DocDueDate"", T0.""DocTotal"", T0.""PaidToDate"", ""TrgetEntry"", T5.""Memo"", T5.""SlpName""  ");
            sb.AppendLine($@"        UNION ALL  ");
            sb.AppendLine($@"        SELECT  'Miami' AS ""BD"", 'PRC', T0.""CardCode"", T2.""CardName"", '', T0.""DocNum"", '', '', T0.""DocDate"", '', T0.""DocDueDate"", T0.""DocTotal"" AS ""TOTAL"", T0.""OpenBal"" * -1, DAYS_BETWEEN(T0.""DocDueDate"", NOW())  ");
            sb.AppendLine($@"                , (CASE WHEN ((DAYS_BETWEEN(T0.""DocDueDate"", NOW()) > 7) AND (T0.""OpenBal"" * -1) > 0) THEN 'HOLD' ELSE '' END) AS ""SITUACION"", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 0  ");
            sb.AppendLine($@"        FROM    {DBLA}.ORCT T0  ");
            sb.AppendLine($@"                INNER JOIN {DBLA}.JDT1 T1 ON T0.""TransId"" = T1.""TransId""  ");
            sb.AppendLine($@"                INNER JOIN {DBLA}.OCRD T2 ON T2.""CardCode"" = T0.""CardCode""  ");
            sb.AppendLine($@"        WHERE   T0.""PayNoDoc"" = 'Y' AND (T0.""CardCode"" <> 'CIMP-008' AND T0.""CardCode"" <> 'CDMC-002') AND T0.""Canceled"" = 'N' AND T0.""DocType"" <> 'A' AND T0.""Canceled"" = 'N' AND T1.""ShortName"" = T0.""CardCode""  ");
            sb.AppendLine($@"                AND T1.""IntrnMatch"" = 0 AND T0.""OpenBal"" > 0  ");
            sb.AppendLine($@"        UNION ALL  ");
            sb.AppendLine($@"        SELECT  'Miami' AS ""BD"", 'PEC', T0.""CardCode"", T1.""CardName"", '', T0.""DocNum"", '', '', T0.""DocDate"", '', T0.""DocDueDate"", T0.""DocTotal"" AS ""TOTAL"", T0.""OpenBal"", DAYS_BETWEEN(NOW(), T0.""DocDueDate"") AS ""Days""  ");
            sb.AppendLine($@"                , (CASE WHEN (DAYS_BETWEEN(NOW(), T0.""DocDueDate"") > 7 AND T0.""OpenBal"" > 0) THEN 'HOLD' ELSE '' END) AS ""SITUACION"", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 0  ");
            sb.AppendLine($@"        FROM    {DBLA}.OVPM T0  ");
            sb.AppendLine($@"                INNER JOIN {DBLA}.OCRD T1 ON T0.""CardCode"" = T1.""CardCode""  ");
            sb.AppendLine($@"                INNER JOIN {DBLA}.JDT1 T2 ON T0.""TransId"" = T2.""TransId""  ");
            sb.AppendLine($@"        WHERE   (T0.""CardCode"" <> 'CIMP-008' AND T0.""CardCode"" <> 'CDMC-002') AND T0.""PayNoDoc"" = 'Y' AND T0.""Canceled"" = 'N' AND T1.""CardType"" = 'C' AND T2.""ShortName"" = T0.""CardCode"" AND T2.""IntrnMatch"" = 0  ");
            sb.AppendLine($@"        UNION ALL  ");
            sb.AppendLine($@"        SELECT  'Miami' AS ""BD"", 'RD', T2.""CardCode"", T2.""CardName"", '', T0.""TransId"", '', '', T0.""RefDate"", T3.""PymntGroup"", T1.""DueDate"", 0, (T1.""Debit"" - T1.""Credit"") AS ""Balance"", DAYS_BETWEEN(T1.""DueDate"", NOW()) AS ""Days""  ");
            sb.AppendLine($@"                , (CASE WHEN (DAYS_BETWEEN(T1.""DueDate"", NOW()) > 7 AND (T1.""Debit"" - T1.""Credit"") > 0) THEN 'HOLD' ELSE '' END) AS ""SITUACION"", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 0  ");
            sb.AppendLine($@"        FROM    {DBLA}.OJDT T0  ");
            sb.AppendLine($@"                INNER JOIN {DBLA}.JDT1 T1 ON T0.""TransId"" = T1.""TransId""  ");
            sb.AppendLine($@"                INNER JOIN {DBLA}.OCRD T2 ON T1.""ShortName"" = T2.""CardCode""  ");
            sb.AppendLine($@"                INNER JOIN {DBLA}.OCTG T3 ON T3.""GroupNum"" = T2.""GroupNum""  ");
            sb.AppendLine($@"        WHERE   T1.""Account"" <> T1.""ShortName"" AND (T2.""CardCode"" <> 'CIMP-008' AND T2.""CardCode"" <> 'CDMC-002') AND T0.""TransType"" = '30' AND T1.""IntrnMatch"" = 0 AND T2.""CardType"" = 'C' AND (T1.""Debit"" - T1.""Credit"") <> 0  ");
            sb.AppendLine($@"                AND T1.""MthDate"" = '' AND T1.""BalDueCred"" <> 0  ");
            sb.AppendLine($@"        UNION ALL  ");
            sb.AppendLine($@"        SELECT DISTINCT 'Miami' AS ""BD"", 'NC', T0.""CardCode"", T2.""CardName"", T4.""WhsName"" AS ""ALMACEN"", T0.""DocNum"", T1.""BaseRef"", '', T0.""DocDate"", '', T0.""DocDueDate"", T0.""DocTotal"" AS ""TOTAL"", (-T0.""DocTotal"" + T0.""PaidToDate"") AS ""Balance""  ");
            sb.AppendLine($@"                , DAYS_BETWEEN(T0.""DocDueDate"", NOW()) AS ""Days"", (CASE WHEN (DAYS_BETWEEN(T0.""DocDueDate"", NOW()) > 7 AND (-T0.""DocTotal"" + T0.""PaidToDate"") > 0) THEN 'HOLD' ELSE '' END) AS ""SITUACION"", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 0  ");
            sb.AppendLine($@"        FROM    {DBLA}.ORIN T0  ");
            sb.AppendLine($@"                INNER JOIN {DBLA}.RIN1 T1 ON T0.""DocEntry"" = T1.""DocEntry""  ");
            sb.AppendLine($@"                INNER JOIN {DBLA}.OCRD T2 ON T2.""CardCode"" = T0.""CardCode""  ");
            sb.AppendLine($@"                LEFT OUTER JOIN {DBLA}.OWHS T4 ON T4.""WhsCode"" = T1.""WhsCode""  ");
            sb.AppendLine($@"        WHERE   T0.""DocStatus"" = 'O' AND (T0.""CardCode"" <> 'CIMP-008' AND T0.""CardCode"" <> 'CDMC-002')  ");
            sb.AppendLine($@"        UNION ALL  ");
            sb.AppendLine($@"        SELECT  ""Subsidiary"", ""Type"", ""CardCode"", ""CardName"", FIRST_VALUE(""Warehouse"" ORDER BY ""DocNum"") AS ""Warehouse"", ""DocNum"", STRING_AGG(""SaleOrder"", ', ') AS ""SaleOrder"", STRING_AGG(""NumAtCard"", ', ') AS ""NumAtCard"", ""DocDate"", ""Terms"", ""DocDueDate"", ""Total"" ");
            sb.AppendLine($@"                , ""Balance"", ""Days"", ""Hold"", ""TrgetEntry"", ""Memo"", ""SlpName"", ""Header"", ""Footer"", SUM(""Margen"") AS ""Margen"", SUM(""TotalCalculo"") AS ""TotalCalculo"", ""PickupDate"", ""IsDeliveryNote"", 0 ");
            sb.AppendLine($@"        FROM    ( SELECT  * ");
            sb.AppendLine($@"                  FROM    ( SELECT DISTINCT 'Iquique' AS ""Subsidiary"", 'FAC' AS ""Type"", T0.""CardCode"", T3.""CardName"", T4.""WhsName"" AS ""Warehouse"", T0.""DocNum"", T1.""BaseRef"" AS ""SaleOrder"", T5.""NumAtCard"", T0.""DocDate"", T2.""PymntGroup"" AS ""Terms""  ");
            sb.AppendLine($@"                                    , T7.""DueDate"" AS ""DocDueDate"", T7.""InsTotal"" AS ""Total"", (T7.""InsTotal"" - T7.""PaidToDate"") AS ""Balance"", DAYS_BETWEEN(T7.""DueDate"", NOW()) AS ""Days"" ");
            sb.AppendLine($@"                                    , (CASE WHEN ((DAYS_BETWEEN(T7.""DueDate"", NOW()) > 7) AND (T7.""InsTotal"" - T7.""PaidToDate"") > 0) THEN 'HOLD' ELSE ' ' END) AS ""Hold"", T1.""TrgetEntry"", T6.""Memo"", T6.""SlpName"", CAST(T5.""Header"" AS varchar(5000)) AS ""Header""  ");
            sb.AppendLine($@"                                    , CAST(T5.""Footer"" AS varchar(5000)) AS ""Footer"", SUM(T1.""Quantity"" * (T1.""PriceAfVAT"" - T1.""StockPrice"")) AS ""Margen""  ");
            sb.AppendLine($@"                                    , SUM(T1.""Quantity"" * T1.""PriceAfVAT"") AS ""TotalCalculo"", T5.U_FECHAR1 AS ""PickupDate"" ");
            sb.AppendLine($@"                                    , ( CASE FIRST_VALUE(T1.""BaseType"" ORDER BY ""LineNum"") WHEN 15 THEN 'Y' ELSE 'N' END ) AS ""IsDeliveryNote"" ");
            sb.AppendLine($@"                            FROM    {DBIQ}.OINV T0  ");
            sb.AppendLine($@"                                    INNER JOIN {DBIQ}.INV1 T1 ON T0.""DocEntry"" = T1.""DocEntry"" AND (T0.""DocTotal"" - T0.""PaidToDate"") <> 0  ");
            sb.AppendLine($@"                                    INNER JOIN {DBIQ}.OCTG T2 ON T0.""GroupNum"" = T2.""GroupNum""  ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBIQ}.OCRD T3 ON T3.""CardCode"" = T0.""CardCode""  ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBIQ}.OWHS T4 ON T4.""WhsCode"" = T1.""WhsCode""  ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBIQ}.ORDR T5 ON T5.""DocEntry"" = T1.""BaseEntry""  ");
            sb.AppendLine($@"                                    INNER JOIN {DBIQ}.OSLP T6 ON T0.""SlpCode"" = T6.""SlpCode""  ");
            sb.AppendLine($@"                                    INNER JOIN {DBIQ}.INV6 T7 ON T7.""DocEntry"" = T0.""DocEntry"" ");
            sb.AppendLine($@"                            WHERE	  T0.""DocSubType"" = '--' AND (T7.""InsTotal"" - T7.""PaidToDate"") > 0 ");
            sb.AppendLine($@"                            GROUP BY T0.""CardCode"", T3.""CardName"", ""WhsName"", T0.""DocNum"", ""BaseRef"", T5.""NumAtCard"", T0.""DocDate"", ""PymntGroup"", T7.""DueDate"", T7.""InsTotal"", T7.""PaidToDate"", ""TrgetEntry"", T6.""Memo"", T6.""SlpName""  ");
            sb.AppendLine($@"                                    , CAST(T5.""Header"" AS varchar(5000)), CAST(T5.""Footer"" AS varchar(5000)), T5.U_FECHAR1 ) a ) a1 ");
            sb.AppendLine($@"        GROUP BY ""Subsidiary"", ""Type"", ""CardCode"", ""CardName"", ""DocNum"", ""DocDate"", ""Terms"", ""DocDueDate"", ""Total"", ""Balance"", ""Days"", ""Hold"", ""TrgetEntry"", ""Memo"", ""SlpName"", ""Header"", ""Footer"", ""PickupDate"", ""IsDeliveryNote"" ");
            sb.AppendLine($@"        UNION ALL  ");
            sb.AppendLine($@"        SELECT DISTINCT 'Iquique' AS ""BD"", 'ND', T0.""CardCode"", T3.""CardName"", T4.""WhsName"" AS ""ALMACEN"", T0.""DocNum"", T1.""BaseRef"", '', T0.""DocDate"", T2.""PymntGroup"", T0.""DocDueDate"", T0.""DocTotal"" AS ""TOTAL""  ");
            sb.AppendLine($@"                , (T0.""DocTotal"" - T0.""PaidToDate"") AS ""Balance"", DAYS_BETWEEN(T0.""DocDueDate"", NOW()) AS ""Days""  ");
            sb.AppendLine($@"                , (CASE WHEN ((DAYS_BETWEEN(T0.""DocDueDate"", NOW()) > 7) AND (T0.""DocTotal"" - T0.""PaidToDate"") > 0) THEN 'HOLD' ELSE '' END) AS ""SITUACION"", T1.""TrgetEntry"", T5.""Memo"", T5.""SlpName"", '' AS ""Header"", '' AS ""Footer""  ");
            sb.AppendLine($@"                , SUM(T1.""Quantity"" * (T1.""PriceAfVAT"" - T1.""StockPrice"")) AS ""Margen"", SUM(T1.""Quantity"" * T1.""PriceAfVAT"") AS ""TotalCalculo"", NULL, 'N', 0  ");
            sb.AppendLine($@"        FROM    {DBIQ}.OINV T0  ");
            sb.AppendLine($@"                INNER JOIN {DBIQ}.INV1 T1 ON T0.""DocEntry"" = T1.""DocEntry""  ");
            sb.AppendLine($@"                INNER JOIN {DBIQ}.OCTG T2 ON T0.""GroupNum"" = T2.""GroupNum""  ");
            sb.AppendLine($@"                LEFT OUTER JOIN {DBIQ}.OCRD T3 ON T3.""CardCode"" = T0.""CardCode""  ");
            sb.AppendLine($@"                LEFT OUTER JOIN {DBIQ}.OWHS T4 ON T4.""WhsCode"" = T1.""WhsCode""  ");
            sb.AppendLine($@"                INNER JOIN {DBIQ}.OSLP T5 ON T0.""SlpCode"" = T5.""SlpCode""  ");
            sb.AppendLine($@"        WHERE   T0.CANCELED = 'N' AND (T0.""CardCode"" <> 'CDMC-002') AND (T1.""TargetType"" <> 14 OR T1.""TargetType"" IS NULL) AND T0.""DocSubType"" = 'DN' AND (T0.""DocTotal"" - T0.""PaidToDate"") <> 0  ");
            sb.AppendLine($@"        GROUP BY T0.""CardCode"", T3.""CardName"", ""WhsName"", T0.""DocNum"", ""BaseRef"", T0.""DocDate"", ""PymntGroup"", T0.""DocDueDate"", T0.""DocTotal"", T0.""PaidToDate"", ""TrgetEntry"", T5.""Memo"", T5.""SlpName""  ");
            sb.AppendLine($@"        UNION ALL  ");
            sb.AppendLine($@"        SELECT  'Iquique' AS ""BD"", 'PRC', T0.""CardCode"", T2.""CardName"", '', T0.""DocNum"", '', '', T0.""DocDate"", '', T0.""DocDueDate"", T0.""DocTotal"" AS ""TOTAL"", T0.""OpenBal"" * -1, DAYS_BETWEEN(T0.""DocDueDate"", NOW())  ");
            sb.AppendLine($@"                , (CASE WHEN ((DAYS_BETWEEN(T0.""DocDueDate"", NOW()) > 7) AND (T0.""OpenBal"" * -1) > 0) THEN 'HOLD' ELSE '' END) AS ""SITUACION"", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 0  ");
            sb.AppendLine($@"        FROM    {DBIQ}.ORCT T0  ");
            sb.AppendLine($@"                INNER JOIN {DBIQ}.JDT1 T1 ON T0.""TransId"" = T1.""TransId""  ");
            sb.AppendLine($@"                INNER JOIN {DBIQ}.OCRD T2 ON T2.""CardCode"" = T0.""CardCode""  ");
            sb.AppendLine($@"        WHERE   T0.""PayNoDoc"" = 'Y' AND T0.""Canceled"" = 'N' AND (T0.""CardCode"" <> 'CDMC-002') AND T0.""DocType"" <> 'A' AND T0.""Canceled"" = 'N' AND T1.""ShortName"" = T0.""CardCode"" AND T1.""IntrnMatch"" = 0 AND T0.""OpenBal"" > 0  ");
            sb.AppendLine($@"        UNION ALL  ");
            sb.AppendLine($@"        SELECT  'Iquique' AS ""BD"", 'PEC', T0.""CardCode"", T1.""CardName"", '', T0.""DocNum"", '', '', T0.""DocDate"", '', T0.""DocDueDate"", T0.""DocTotal"" AS ""TOTAL"", T0.""OpenBal"", DAYS_BETWEEN(NOW(), T0.""DocDueDate"") AS ""Days""  ");
            sb.AppendLine($@"                , (CASE WHEN (DAYS_BETWEEN(NOW(), T0.""DocDueDate"") > 7 AND T0.""OpenBal"" > 0) THEN 'HOLD' ELSE '' END) AS ""SITUACION"", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 0  ");
            sb.AppendLine($@"        FROM    {DBIQ}.OVPM T0  ");
            sb.AppendLine($@"                INNER JOIN {DBIQ}.OCRD T1 ON T0.""CardCode"" = T1.""CardCode""  ");
            sb.AppendLine($@"                INNER JOIN {DBIQ}.JDT1 T2 ON T0.""TransId"" = T2.""TransId""  ");
            sb.AppendLine($@"        WHERE   T0.""PayNoDoc"" = 'Y' AND T0.""Canceled"" = 'N' AND (T0.""CardCode"" <> 'CDMC-002') AND T1.""CardType"" = 'C' AND T2.""ShortName"" = T0.""CardCode"" AND T2.""IntrnMatch"" = 0  ");
            sb.AppendLine($@"        UNION ALL  ");
            sb.AppendLine($@"        SELECT  'Iquique', 'RD', T2.""CardCode"", T2.""CardName"", '', T0.""TransId"", '', '', T0.""RefDate"", T3.""PymntGroup"", T1.""DueDate"", 0, (T1.""Debit"" - T1.""Credit"") AS ""Balance"", DAYS_BETWEEN(T1.""DueDate"", NOW()) AS ""Days""  ");
            sb.AppendLine($@"                , (CASE WHEN (DAYS_BETWEEN(T1.""DueDate"", NOW()) > 7 AND (T1.""Debit"" - T1.""Credit"") > 0) THEN 'HOLD' ELSE '' END) AS ""SITUACION"", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 0  ");
            sb.AppendLine($@"        FROM    {DBIQ}.OJDT T0  ");
            sb.AppendLine($@"                INNER JOIN {DBIQ}.JDT1 T1 ON T0.""TransId"" = T1.""TransId""  ");
            sb.AppendLine($@"                INNER JOIN {DBIQ}.OCRD T2 ON T1.""ShortName"" = T2.""CardCode""  ");
            sb.AppendLine($@"                INNER JOIN {DBIQ}.OCTG T3 ON T3.""GroupNum"" = T2.""GroupNum""  ");
            sb.AppendLine($@"        WHERE   T1.""Account"" <> T1.""ShortName"" AND T0.""TransType"" = '30' AND (T2.""CardCode"" <> 'CDMC-002') AND T1.""IntrnMatch"" = 0 AND T2.""CardType"" = 'C' AND (T1.""Debit"" - T1.""Credit"") <> 0 AND T1.""MthDate"" = '' AND T1.""BalDueCred"" <> 0  ");
            sb.AppendLine($@"        UNION ALL  ");
            sb.AppendLine($@"        SELECT DISTINCT 'Iquique' AS ""BD"", 'NC', T0.""CardCode"", T2.""CardName"", T4.""WhsName"" AS ""ALMACEN"", T0.""DocNum"", T1.""BaseRef"", '', T0.""DocDate"", '', T0.""DocDueDate"", T0.""DocTotal"" AS ""TOTAL"", (-T0.""DocTotal"" + T0.""PaidToDate"") AS ""Balance""  ");
            sb.AppendLine($@"                , DAYS_BETWEEN(T0.""DocDueDate"", NOW()) AS ""Days"", (CASE WHEN (DAYS_BETWEEN(T0.""DocDueDate"", NOW()) > 7 AND (-T0.""DocTotal"" + T0.""PaidToDate"") > 0) THEN 'HOLD' ELSE '' END) AS ""SITUACION"", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 0  ");
            sb.AppendLine($@"        FROM    {DBIQ}.ORIN T0  ");
            sb.AppendLine($@"                INNER JOIN {DBIQ}.RIN1 T1 ON T0.""DocEntry"" = T1.""DocEntry""  ");
            sb.AppendLine($@"                INNER JOIN {DBIQ}.OCRD T2 ON T2.""CardCode"" = T0.""CardCode""  ");
            sb.AppendLine($@"                LEFT OUTER JOIN {DBIQ}.OWHS T4 ON T4.""WhsCode"" = T1.""WhsCode""  ");
            sb.AppendLine($@"        WHERE   T0.""DocStatus"" = 'O' AND (T0.""CardCode"" <> 'CDMC-002')  ");
            sb.AppendLine($@"        UNION ALL  ");
            sb.AppendLine($@"        SELECT  ""Subsidiary"", ""Type"", ""CardCode"", ""CardName"", FIRST_VALUE(""Warehouse"" ORDER BY ""DocNum"") AS ""Warehouse"", ""DocNum"", STRING_AGG(""SaleOrder"", ', ') AS ""SaleOrder"", STRING_AGG(""NumAtCard"", ', ') AS ""NumAtCard"", ""DocDate"", ""Terms"", ""DocDueDate"", ""Total"" ");
            sb.AppendLine($@"                , ""Balance"", ""Days"", ""Hold"", ""TrgetEntry"", ""Memo"", ""SlpName"", ""Header"", ""Footer"", SUM(""Margen"") AS ""Margen"", SUM(""TotalCalculo"") AS ""TotalCalculo"", ""PickupDate"", ""IsDeliveryNote"", FIRST_VALUE(""BillSerie"" ORDER BY ""DocNum"") AS ""BillSerie""  ");
            sb.AppendLine($@"        FROM    ( SELECT  * ");
            sb.AppendLine($@"                  FROM    ( SELECT DISTINCT 'Santa Cruz' AS ""Subsidiary"", 'FAC' AS ""Type"", T0.""CardCode"", T3.""CardName"", T4.""WhsName"" AS ""Warehouse"", T0.""DocNum"", T1.""BaseRef"" AS ""SaleOrder"", T5.""NumAtCard"", T0.""DocDate"", T2.""PymntGroup"" AS ""Terms""  ");
            sb.AppendLine($@"                                    , T7.""DueDate"" AS ""DocDueDate"", T7.""InsTotal"" AS ""Total"", (T7.""InsTotal"" - T7.""PaidToDate"") AS ""Balance"", DAYS_BETWEEN(T7.""DueDate"", NOW()) AS ""Days"" ");
            sb.AppendLine($@"                                    , (CASE WHEN ((DAYS_BETWEEN(T7.""DueDate"", NOW()) > 7) AND (T7.""InsTotal"" - T7.""PaidToDate"") > 0) THEN 'HOLD' ELSE ' ' END) AS ""Hold"", T1.""TrgetEntry"", T6.""Memo"", T6.""SlpName"", CAST(T5.""Header"" AS varchar(5000)) AS ""Header""  ");
            sb.AppendLine($@"                                    , CAST(T5.""Footer"" AS varchar(5000)) AS ""Footer"", SUM((CASE WHEN T1.""WhsCode"" = 'ZFSCZ' THEN T1.""Quantity"" * (T1.""PriceAfVAT"" - T1.""StockPrice"") ELSE T1.""Quantity"" * ((0.84 * T1.""PriceAfVAT"") - T1.""StockPrice"") END)) AS ""Margen""  ");
            sb.AppendLine($@"                                    , SUM((CASE WHEN T1.""WhsCode"" = 'ZFSCZ' THEN T1.""Quantity"" * T1.""PriceAfVAT"" ELSE T1.""Quantity"" * 0.84 * T1.""PriceAfVAT"" END)) AS ""TotalCalculo"", T5.U_FECHAR1 AS ""PickupDate"" ");
            sb.AppendLine($@"                                    , ( CASE FIRST_VALUE(T1.""BaseType"" ORDER BY ""LineNum"") WHEN 15 THEN 'Y' ELSE 'N' END ) AS ""IsDeliveryNote"", FIRST_VALUE(t0.""Series"" ORDER BY t0.""DocEntry"") AS ""BillSerie""  ");
            sb.AppendLine($@"                            FROM    {DBSA}.OINV T0  ");
            sb.AppendLine($@"                                    INNER JOIN {DBSA}.INV1 T1 ON T0.""DocEntry"" = T1.""DocEntry"" AND (T0.""DocTotal"" - T0.""PaidToDate"") <> 0  ");
            sb.AppendLine($@"                                    INNER JOIN {DBSA}.OCTG T2 ON T0.""GroupNum"" = T2.""GroupNum""  ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBSA}.OCRD T3 ON T3.""CardCode"" = T0.""CardCode""  ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBSA}.OWHS T4 ON T4.""WhsCode"" = T1.""WhsCode""  ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBSA}.ORDR T5 ON T5.""DocEntry"" = T1.""BaseEntry""  ");
            sb.AppendLine($@"                                    INNER JOIN {DBSA}.OSLP T6 ON T0.""SlpCode"" = T6.""SlpCode""  ");
            sb.AppendLine($@"                                    INNER JOIN {DBSA}.INV6 T7 ON T7.""DocEntry"" = T0.""DocEntry"" ");
            sb.AppendLine($@"                            WHERE	 T0.""DocSubType"" = '--' AND (T7.""InsTotal"" - T7.""PaidToDate"") > 0 ");
            sb.AppendLine($@"                            GROUP BY T0.""CardCode"", T3.""CardName"", ""WhsName"", T0.""DocNum"", ""BaseRef"", T5.""NumAtCard"", T0.""DocDate"", ""PymntGroup"", T7.""DueDate"", T7.""InsTotal"", T7.""PaidToDate"", ""TrgetEntry"", T6.""Memo"", T6.""SlpName""  ");
            sb.AppendLine($@"                                    , CAST(T5.""Header"" AS varchar(5000)), CAST(T5.""Footer"" AS varchar(5000)), T5.U_FECHAR1 ) a ) a1 ");
            sb.AppendLine($@"        GROUP BY ""Subsidiary"", ""Type"", ""CardCode"", ""CardName"", ""DocNum"", ""DocDate"", ""Terms"", ""DocDueDate"", ""Total"", ""Balance"", ""Days"", ""Hold"", ""TrgetEntry"", ""Memo"", ""SlpName"", ""Header"", ""Footer"", ""PickupDate"", ""IsDeliveryNote"" ");
            sb.AppendLine($@"        UNION ALL  ");
            sb.AppendLine($@"        SELECT DISTINCT 'Santa Cruz' AS ""BD"", 'ND', T0.""CardCode"", T3.""CardName"", T4.""WhsName"", T0.""DocNum"", T1.""BaseRef"", '', T0.""DocDate"", T2.""PymntGroup"", T7.""DueDate"", T7.""InsTotal"" AS ""TOTAL"", (T7.""InsTotal"" - T7.""PaidToDate"") AS ""Balance""  ");
            sb.AppendLine($@"                , DAYS_BETWEEN(T7.""DueDate"", NOW()) AS ""Days"", (CASE WHEN ((DAYS_BETWEEN(T7.""DueDate"", NOW()) > 7) AND (T7.""InsTotal"" - T7.""PaidToDate"") > 0) THEN 'HOLD' ELSE '' END) AS ""SITUACION"", T1.""TrgetEntry"", T5.""Memo"", T5.""SlpName""  ");
            sb.AppendLine($@"                , '' AS ""Header"", '' AS ""Footer"", SUM((CASE WHEN T1.""WhsCode"" = 'ZFSCZ' THEN T1.""Quantity"" * (T1.""PriceAfVAT"" - T1.""StockPrice"") ELSE T1.""Quantity"" * ((0.84 * T1.""PriceAfVAT"") - T1.""StockPrice"") END)) AS ""Margen""  ");
            sb.AppendLine($@"                , SUM((CASE WHEN T1.""WhsCode"" = 'ZFSCZ' THEN T1.""Quantity"" * T1.""PriceAfVAT"" ELSE T1.""Quantity"" * 0.84 * T1.""PriceAfVAT"" END)) AS ""TotalCalculo"", NULL, 'N', t0.""Series"" AS ""BillSerie""  ");
            sb.AppendLine($@"        FROM    {DBSA}.OINV T0  ");
            sb.AppendLine($@"                INNER JOIN {DBSA}.INV1 T1 ON T0.""DocEntry"" = T1.""DocEntry""  ");
            sb.AppendLine($@"                INNER JOIN {DBSA}.OCTG T2 ON T0.""GroupNum"" = T2.""GroupNum""  ");
            sb.AppendLine($@"                LEFT OUTER JOIN {DBSA}.OCRD T3 ON T3.""CardCode"" = T0.""CardCode""  ");
            sb.AppendLine($@"                LEFT OUTER JOIN {DBSA}.OWHS T4 ON T4.""WhsCode"" = T1.""WhsCode""  ");
            sb.AppendLine($@"                INNER JOIN {DBSA}.OSLP T5 ON T0.""SlpCode"" = T5.""SlpCode""  ");
            sb.AppendLine($@"                INNER JOIN {DBSA}.INV6 T7 ON T7.""DocEntry"" = T0.""DocEntry"" ");
            sb.AppendLine($@"        WHERE   T0.CANCELED = 'N' AND (T1.""TargetType"" <> 14 OR T1.""TargetType"" IS NULL) AND T0.""DocSubType"" = 'DN' AND (T0.""DocTotal"" - T0.""PaidToDate"") <> 0  ");
            sb.AppendLine($@"        GROUP BY T0.""CardCode"", T3.""CardName"", ""WhsName"", T0.""DocNum"", ""BaseRef"", T0.""DocDate"", ""PymntGroup"", T7.""DueDate"", T7.""InsTotal"", T7.""PaidToDate"", ""TrgetEntry"", T5.""Memo"", T5.""SlpName"", t0.""Series""  ");
            sb.AppendLine($@"        UNION ALL  ");
            sb.AppendLine($@"        SELECT  'Santa Cruz' AS ""BD"", 'PRC', T0.""CardCode"", T2.""CardName"", '', T0.""DocNum"", '', '', T0.""DocDate"", '', T0.""DocDueDate"", T0.""DocTotal"" AS ""TOTAL"", T0.""OpenBal"" * -1, DAYS_BETWEEN(T0.""DocDueDate"", NOW())  ");
            sb.AppendLine($@"                , (CASE WHEN ((DAYS_BETWEEN(T0.""DocDueDate"", NOW()) > 7) AND (T0.""OpenBal"" * -1) > 0) THEN 'HOLD' ELSE '' END) AS ""SITUACION"", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 0  ");
            sb.AppendLine($@"        FROM    {DBSA}.ORCT T0  ");
            sb.AppendLine($@"                INNER JOIN {DBSA}.JDT1 T1 ON T0.""TransId"" = T1.""TransId""  ");
            sb.AppendLine($@"                INNER JOIN {DBSA}.OCRD T2 ON T2.""CardCode"" = T0.""CardCode""  ");
            sb.AppendLine($@"        WHERE   T0.""PayNoDoc"" = 'Y' AND T0.""Canceled"" = 'N' AND T0.""DocType"" <> 'A' AND T0.""Canceled"" = 'N' AND T1.""ShortName"" = T0.""CardCode"" AND T1.""IntrnMatch"" = 0 AND T0.""OpenBal"" > 0  ");
            sb.AppendLine($@"        UNION ALL  ");
            sb.AppendLine($@"        SELECT  'Santa Cruz' AS ""BD"", 'PEC', T0.""CardCode"", T1.""CardName"", '', T0.""DocNum"", '', '', T0.""DocDate"", '', T0.""DocDueDate"", T0.""DocTotal"" AS ""TOTAL"", T0.""OpenBal"", DAYS_BETWEEN(NOW(), T0.""DocDueDate"") AS ""Days""  ");
            sb.AppendLine($@"                , (CASE WHEN (DAYS_BETWEEN(NOW(), T0.""DocDueDate"") > 7 AND T0.""OpenBal"" > 0) THEN 'HOLD' ELSE '' END) AS ""SITUACION"", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 0  ");
            sb.AppendLine($@"        FROM    {DBSA}.OVPM T0  ");
            sb.AppendLine($@"                INNER JOIN {DBSA}.OCRD T1 ON T0.""CardCode"" = T1.""CardCode""  ");
            sb.AppendLine($@"                INNER JOIN {DBSA}.JDT1 T2 ON T0.""TransId"" = T2.""TransId""  ");
            sb.AppendLine($@"        WHERE   T0.""PayNoDoc"" = 'Y' AND T0.""Canceled"" = 'N' AND T1.""CardType"" = 'C' AND T2.""ShortName"" = T0.""CardCode"" AND T2.""IntrnMatch"" = 0  ");
            sb.AppendLine($@"        UNION  ");
            sb.AppendLine($@"        SELECT 'Santa Cruz' AS ""BD"", 'RD', T2.""CardCode"", T2.""CardName"", '', T0.""TransId"", '', '', T0.""RefDate"", T3.""PymntGroup"", T1.""DueDate"", 0, (T1.""Debit"" - T1.""Credit"") AS ""Balance"", DAYS_BETWEEN(T1.""DueDate"", NOW()) AS ""Days""  ");
            sb.AppendLine($@"                , (CASE WHEN (DAYS_BETWEEN(T1.""DueDate"", NOW()) > 7 AND (T1.""Debit"" - T1.""Credit"") > 0) THEN 'HOLD' ELSE '' END) AS ""SITUACION"", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 0  ");
            sb.AppendLine($@"        FROM    {DBSA}.OJDT T0  ");
            sb.AppendLine($@"                INNER JOIN {DBSA}.JDT1 T1 ON T0.""TransId"" = T1.""TransId""  ");
            sb.AppendLine($@"                INNER JOIN {DBSA}.OCRD T2 ON T1.""ShortName"" = T2.""CardCode""  ");
            sb.AppendLine($@"                INNER JOIN {DBSA}.OCTG T3 ON T3.""GroupNum"" = T2.""GroupNum""  ");
            sb.AppendLine($@"        WHERE   T1.""Account"" <> T1.""ShortName"" AND T0.""TransType"" = '30' AND T1.""IntrnMatch"" = 0 AND T2.""CardType"" = 'C' AND (T1.""Debit"" - T1.""Credit"") <> 0 AND T1.""MthDate"" = '' AND T1.""BalDueCred"" <> 0  ");
            sb.AppendLine($@"        UNION  ");
            sb.AppendLine($@"        SELECT DISTINCT 'Santa Cruz' AS ""BD"", 'NC', T0.""CardCode"", T2.""CardName"", T4.""WhsName"", T0.""DocNum"", T1.""BaseRef"", '', T0.""DocDate"", '', T0.""DocDueDate"", T0.""DocTotal"" AS ""TOTAL"", (-T0.""DocTotal"" + T0.""PaidToDate"") AS ""Balance""  ");
            sb.AppendLine($@"                , DAYS_BETWEEN(T0.""DocDueDate"", NOW()) AS ""Days"", (CASE WHEN (DAYS_BETWEEN(T0.""DocDueDate"", NOW()) > 7 AND (-T0.""DocTotal"" + T0.""PaidToDate"") > 0) THEN 'HOLD' ELSE '' END) AS ""SITUACION"", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N', 0  ");
            sb.AppendLine($@"        FROM    {DBSA}.ORIN T0  ");
            sb.AppendLine($@"                INNER JOIN {DBSA}.RIN1 T1 ON T0.""DocEntry"" = T1.""DocEntry""  ");
            sb.AppendLine($@"                INNER JOIN {DBSA}.OCRD T2 ON T2.""CardCode"" = T0.""CardCode""  ");
            sb.AppendLine($@"                LEFT OUTER JOIN {DBSA}.OWHS T4 ON T4.""WhsCode"" = T1.""WhsCode""  ");
            sb.AppendLine($@"        WHERE   T0.""DocStatus"" = 'O' ");
            sb.AppendLine($@"    ) AS TA  ");
            sb.AppendLine($@"WHERE	{filter} ");
            sb.AppendLine($@"ORDER By {GetOrder(Order)}");

            IEnumerable<BEA.StateAccountItem> items = SQLList<BEA.StateAccountItem>(sb.ToString());
            return items;
        }

        public IEnumerable<BEA.Seller> ListProductManagers()
        {
            var sb = new StringBuilder();
            sb.AppendLine($@"SELECT      * ");
            sb.AppendLine($@"FROM        ( SELECT    TB.""Memo"" AS ""Name"", TB.""SlpName"" AS ""ShortName"" ");
            sb.AppendLine($@"              FROM      ( SELECT    T0.""CardCode"", T3.""CardName"", T0.""SlpCode"" ");
            sb.AppendLine($@"                          FROM      {DBIQ}.OPCH T0 ");
            sb.AppendLine($@"                                    INNER JOIN {DBIQ}.OCRD T3 ON T3.""CardCode"" = T0.""CardCode"" ");
            sb.AppendLine($@"                          WHERE     (( T0.""DocTotal"" - T0.""PaidToDate"" ) * -1 ) <> 0 AND ( T0.""CardCode"" LIKE 'B%' OR T0.""CardCode"" LIKE 'M%' ) AND T0.""DocSubType"" = '--' ");
            sb.AppendLine($@"                          UNION ");
            sb.AppendLine($@"                          SELECT    T0.""CardCode"", T0.""CardName"", T0.""SlpCode"" ");
            sb.AppendLine($@"                          FROM      {DBIQ}.OPCH T0 ");
            sb.AppendLine($@"                          WHERE     T0.CANCELED = 'N' AND T0.""DocSubType"" = 'DM' AND ( T0.""DocTotal"" - T0.""PaidToDate"" ) * -1 <> 0 AND ( T0.""CardCode"" LIKE 'B%' OR T0.""CardCode"" LIKE 'M%' )) AS TA ");
            sb.AppendLine($@"                        INNER JOIN {DBIQ}.OSLP TB ON TB.""SlpCode"" = TA.""SlpCode"" ");
            sb.AppendLine($@"              WHERE		TB.""Memo"" IS NOT NULL           ");
            sb.AppendLine($@"              UNION ");
            sb.AppendLine($@"              SELECT    TB.""Memo"", TB.""SlpName"" ");
            sb.AppendLine($@"              FROM      ( SELECT    T0.""CardCode"", T3.""CardName"", T0.""SlpCode"" ");
            sb.AppendLine($@"                          FROM      {DBLA}.OPCH T0 ");
            sb.AppendLine($@"                                    INNER JOIN {DBLA}.OCRD T3 ON T3.""CardCode"" = T0.""CardCode"" ");
            sb.AppendLine($@"                          WHERE     (( T0.""DocTotal"" - T0.""PaidToDate"" ) * -1 ) <> 0 AND T0.""DocSubType"" = '--' AND ( T0.""CardCode"" LIKE 'B%' OR T0.""CardCode"" LIKE 'M%' ) ");
            sb.AppendLine($@"                          UNION ");
            sb.AppendLine($@"                          SELECT    T0.""CardCode"", T0.""CardName"", T0.""SlpCode"" ");
            sb.AppendLine($@"                          FROM      {DBLA}.OPCH T0 ");
            sb.AppendLine($@"                          WHERE     T0.CANCELED = 'N' AND T0.""DocSubType"" = 'DM' AND ( T0.""DocTotal"" - T0.""PaidToDate"" ) * -1 <> 0 AND ( T0.""CardCode"" LIKE 'B%' OR T0.""CardCode"" LIKE 'M%' )) AS TA ");
            sb.AppendLine($@"                        INNER JOIN {DBLA}.OSLP TB ON TB.""SlpCode"" = TA.""SlpCode"" ");
            sb.AppendLine($@"			  WHERE		TB.""Memo"" IS NOT NULL ");
            sb.AppendLine($@"              UNION ");
            sb.AppendLine($@"              SELECT    TB.""Memo"", TB.""SlpName"" ");
            sb.AppendLine($@"              FROM      ( SELECT    T0.""CardCode"", T3.""CardName"", T0.""SlpCode"" ");
            sb.AppendLine($@"                          FROM      {DBSA}.OPCH T0 ");
            sb.AppendLine($@"                                    INNER JOIN {DBSA}.OCRD T3 ON T3.""CardCode"" = T0.""CardCode"" ");
            sb.AppendLine($@"                          WHERE     (( T0.""DocTotal"" - T0.""PaidToDate"" ) * -1 ) <> 0 AND T0.""DocSubType"" = '--' AND ( T0.""CardCode"" LIKE 'B%' OR T0.""CardCode"" LIKE 'M%' ) ");
            sb.AppendLine($@"                          UNION ");
            sb.AppendLine($@"                          SELECT    T0.""CardCode"", T0.""CardName"", T0.""SlpCode"" ");
            sb.AppendLine($@"                          FROM      {DBSA}.OPCH T0 ");
            sb.AppendLine($@"                          WHERE     T0.CANCELED = 'N' AND T0.""DocSubType"" = 'DM' AND ( T0.""DocTotal"" - T0.""PaidToDate"" ) * -1 <> 0 AND ( T0.""CardCode"" LIKE 'B%' OR T0.""CardCode"" LIKE 'M%' )) AS TA ");
            sb.AppendLine($@"            INNER JOIN {DBSA}.OSLP TB ON TB.""SlpCode"" = TA.""SlpCode"" ");
            sb.AppendLine($@"            WHERE		TB.""Memo"" IS NOT NULL ) a ");
            sb.AppendLine($@"ORDER BY    2 ");

            IEnumerable<BEA.Seller> items = SQLList<BEA.Seller>(sb.ToString());
            return items;
        }

        public IEnumerable<BEA.ProviderStateAccountItem> ListStateAccountProvider(List<Field> FilterList, string Order)
        {
            var filter = GetFilter(FilterList?.ToArray());

            var sb = new StringBuilder();
            sb.AppendLine($@"SELECT      * ");
            sb.AppendLine($@"FROM        ( SELECT    'Iquique' AS ""Subsidiary"", TA.""Type"", TA.""DocNum"", TA.""CardCode"" AS ""ProviderCode"", TA.""CardName"" AS ""ProviderName"" ");
            sb.AppendLine($@"                        , ( CASE TA.""Type"" WHEN 'Factura' THEN TA.""DocNum"" END ) AS ""BillProvider"" ");
            sb.AppendLine($@"                        , TA.""DocBase"", TA.""DocDate"", TA.""Terms"", TA.""DocDueDate"", TA.""DocTotal"" ");
            sb.AppendLine($@"                        , TA.""Balance"", TA.""Days"", ( CASE WHEN ( TA.""Type"" = 'Factura' AND  TA.""Days"" <= 0 ) THEN 'Vigente' ");
            sb.AppendLine($@"                                                                            WHEN ( TA.""Type"" = 'Factura' AND TA.""Days"" > 0 ) THEN 'En Mora' ");
            sb.AppendLine($@"                                                                            WHEN ( TA.""Type"" = 'Pago Efectuado' ) THEN 'Abono' END ) AS ""State"" ");
            sb.AppendLine($@"                        , TA.""BillNumber"", tb.""Memo"" AS ""ProductManager"", tb.""SlpName"" AS ""ProductManagerShort"" ");
            sb.AppendLine($@"              FROM      ( SELECT    'Factura' AS ""Type"", T0.""CardCode"", T3.""CardName"" ");
            sb.AppendLine($@"                                    , T0.""DocNum"", T1.""BaseRef"" AS ""DocBase"", T0.""NumAtCard"" AS ""BillNumber"", CAST(T0.""DocDate"" AS DATE) AS ""DocDate"" ");
            sb.AppendLine($@"                                    , T2.""PymntGroup"" AS ""Terms"", CAST(T0.""DocDueDate"" AS DATE) AS ""DocDueDate"", T0.""DocTotal"" * -1 AS ""DocTotal"" ");
            sb.AppendLine($@"                                    , (( T0.""DocTotal"" - T0.""PaidToDate"" ) * -1 ) AS ""Balance"", DAYS_BETWEEN(T0.""DocDueDate"", NOW()) AS ""Days"", T0.""SlpCode"" ");
            sb.AppendLine($@"                          FROM      {DBIQ}.OPCH T0 ");
            sb.AppendLine($@"                                    INNER JOIN {DBIQ}.PCH1 T1 ON T1.""DocEntry"" = T0.""DocEntry"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBIQ}.OCTG T2 ON T0.""GroupNum"" = T2.""GroupNum"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBIQ}.OCRD T3 ON T3.""CardCode"" = T0.""CardCode"" ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBIQ}.CRD1 T4 ON T4.""CardCode"" = T0.""CardCode"" AND  T4.""AdresType"" = 'B' AND  ( T4.""LineNum"" = 0 OR   T4.""LineNum"" = 1 ) ");
            sb.AppendLine($@"                          WHERE     (( T0.""DocTotal"" - T0.""PaidToDate"" ) * -1 ) <> 0 ");
            sb.AppendLine($@"                                    AND T0.""DocSubType"" = '--' AND ( T0.""CardCode"" LIKE 'B%' OR T0.""CardCode"" LIKE 'M%' ) ");
            sb.AppendLine($@"                          GROUP BY  T0.""DocNum"", T0.""CardCode"", T0.""SlpCode"", T3.""CardName"", T1.""BaseRef"", T0.""DocDate"", T0.""DocDueDate"", T0.""DocTotal"" ");
            sb.AppendLine($@"                                    , T2.""PymntGroup"", T0.""NumAtCard"", (( T0.""DocTotal"" - T0.""PaidToDate"" ) * -1 ) ");
            sb.AppendLine($@"                          UNION ");
            sb.AppendLine($@"                          SELECT    'Nota de Debito', T0.""CardCode"", T0.""CardName"", T0.""DocNum"", T1.""BaseRef"" ");
            sb.AppendLine($@"                                    , T0.""NumAtCard"", CAST(T0.""DocDate"" AS DATE), T2.""PymntGroup"", CAST(T0.""DocDueDate"" AS DATE), T0.""DocTotal"" ");
            sb.AppendLine($@"                                    , (( T0.""DocTotal"" - T0.""PaidToDate"" ) * -1 ), DAYS_BETWEEN(T0.""DocDueDate"", NOW()), T0.""SlpCode"" ");
            sb.AppendLine($@"                          FROM      {DBIQ}.OPCH T0 ");
            sb.AppendLine($@"                                    INNER JOIN {DBIQ}.PCH1 T1 ON T1.""DocEntry"" = T0.""DocEntry"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBIQ}.OCTG T2 ON T0.""GroupNum"" = T2.""GroupNum"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBIQ}.OCRD T3 ON T3.""CardCode"" = T0.""CardCode"" ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBIQ}.CRD1 T4 ON T4.""CardCode"" = T0.""CardCode"" AND T4.""AdresType"" = 'B' AND  ( T4.""LineNum"" = 0 OR   T4.""LineNum"" = 1 ) ");
            sb.AppendLine($@"                          WHERE     T0.CANCELED = 'N' ");
            sb.AppendLine($@"                                    AND T0.""DocSubType"" = 'DM' ");
            sb.AppendLine($@"                                    AND ( T0.""DocTotal"" - T0.""PaidToDate"" ) * -1 <> 0 ");
            sb.AppendLine($@"                                    AND ( T0.""CardCode"" LIKE 'B%' OR T0.""CardCode"" LIKE 'M%' ) ");
            sb.AppendLine($@"                          GROUP BY  T0.""DocNum"", T0.""CardName"", T0.""SlpCode"", T1.""BaseRef"", CAST(T0.""DocDate"" AS DATE), CAST(T0.""DocDueDate"" AS DATE), T0.""DocTotal"" ");
            sb.AppendLine($@"                                    , DAYS_BETWEEN(T0.""DocDueDate"", NOW()), T0.""CardCode"", T3.""CardFName"", T2.""PymntGroup"", T0.""NumAtCard"", ( T0.""DocTotal"" - T0.""PaidToDate"" ) ");
            sb.AppendLine($@"                          UNION ");
            sb.AppendLine($@"                          SELECT    'Pago Recibido', T0.""CardCode"", T0.""CardName"", T0.""DocNum"", '', '', CAST(T0.""DocDate"" AS DATE), '' ");
            sb.AppendLine($@"                                    , CAST(T0.""DocDueDate"" AS DATE), T0.""DocTotal"" * -1, T0.""OpenBal"" * -1, DAYS_BETWEEN(T0.""DocDueDate"", NOW()), -1 ");
            sb.AppendLine($@"                          FROM      {DBIQ}.ORCT T0 ");
            sb.AppendLine($@"                                    INNER JOIN {DBIQ}.JDT1 T1 ON T0.""TransId"" = T1.""TransId"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBIQ}.OCRD T2 ON T2.""CardCode"" = T0.""CardCode"" ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBIQ}.CRD1 T4 ON T4.""CardCode"" = T0.""CardCode"" AND  T4.""AdresType"" = 'B' AND  ( T4.""LineNum"" = 0 OR   T4.""LineNum"" = 1 ) ");
            sb.AppendLine($@"                          WHERE     T0.""PayNoDoc"" = 'Y' AND T0.""Canceled"" = 'N' AND T0.""DocType"" = 'S' AND T0.""Canceled"" = 'N' AND T1.""ShortName"" = T0.""CardCode"" ");
            sb.AppendLine($@"                                    AND T1.""IntrnMatch"" = 0 AND ( T0.""CardCode"" LIKE 'B%' OR T0.""CardCode"" LIKE 'M%' ) ");
            sb.AppendLine($@"                          UNION ");
            sb.AppendLine($@"                          SELECT    'Pago Efectuado', T0.""CardCode"", T0.""CardName"", T0.""DocNum"", '', '', CAST(T0.""DocDate"" AS DATE), '' ");
            sb.AppendLine($@"                                    , CAST(T0.""DocDueDate"" AS DATE), T0.""DocTotal"", T0.""OpenBal"", DAYS_BETWEEN(T0.""DocDueDate"", NOW()) AS ""Days"", -1 ");
            sb.AppendLine($@"                          FROM      {DBIQ}.OVPM T0 ");
            sb.AppendLine($@"                                    INNER JOIN {DBIQ}.OCRD T1 ON T0.""CardCode"" = T1.""CardCode"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBIQ}.JDT1 T2 ON T0.""TransId"" = T2.""TransId"" ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBIQ}.CRD1 T4 ON T4.""CardCode"" = T0.""CardCode"" AND  T4.""AdresType"" = 'B' AND  ( T4.""LineNum"" = 0 OR   T4.""LineNum"" = 1 ) ");
            sb.AppendLine($@"                          WHERE     T0.""PayNoDoc"" = 'Y' AND T0.""Canceled"" = 'N' AND T1.""CardType"" = 'S' AND T2.""ShortName"" = T0.""CardCode"" AND T2.""IntrnMatch"" = 0 ");
            sb.AppendLine($@"                                    AND T0.""OpenBal"" > 0 AND ( T0.""CardCode"" LIKE 'B%' OR T0.""CardCode"" LIKE 'M%' ) ");
            sb.AppendLine($@"                          UNION ");
            sb.AppendLine($@"                          SELECT    'Registro Diario', T2.""CardCode"", T2.""CardName"", T0.""TransId"", '', '', CAST(T0.""RefDate"" AS DATE) ");
            sb.AppendLine($@"                                    , T3.""PymntGroup"", CAST(T1.""DueDate"" AS DATE), 0, (( T1.""Credit"" - T1.""Debit"" ) * -1 ) AS ""Balance"", DAYS_BETWEEN(T1.""DueDate"", NOW()) AS ""Days"", -1 ");
            sb.AppendLine($@"                          FROM      {DBIQ}.OJDT T0 ");
            sb.AppendLine($@"                                    INNER JOIN {DBIQ}.JDT1 T1 ON T0.""TransId"" = T1.""TransId"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBIQ}.OCRD T2 ON T1.""ShortName"" = T2.""CardCode"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBIQ}.OCTG T3 ON T3.""GroupNum"" = T2.""GroupNum"" ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBIQ}.CRD1 T4 ON T4.""CardCode"" = T2.""CardCode"" AND  T4.""AdresType"" = 'B' AND  ( T4.""LineNum"" = 0 OR   T4.""LineNum"" = 1 ) ");
            sb.AppendLine($@"                          WHERE     T1.""Account"" <> T1.""ShortName"" AND T0.""TransType"" = '30' AND T1.""IntrnMatch"" = 0 AND T2.""CardType"" = 'S' AND (( T1.""Credit"" - T1.""Debit"" ) * -1 ) <> 0 ");
            sb.AppendLine($@"                                    AND T1.""MthDate"" = '' AND ( T2.""CardCode"" LIKE 'B%' OR T2.""CardCode"" LIKE 'M%' ) ");
            sb.AppendLine($@"                          UNION ");
            sb.AppendLine($@"                          SELECT    'Nota de Credito', T0.""CardCode"", T0.""CardName"", T0.""DocNum"", '', T0.""NumAtCard"", CAST(T0.""DocDate"" AS DATE), '' ");
            sb.AppendLine($@"                                    , CAST(T0.""DocDueDate"" AS DATE), T0.""DocTotal"", (( -T0.""DocTotal"" + T0.""PaidToDate"" ) * -1 ) AS ""Balance"" ");
            sb.AppendLine($@"                                    , DAYS_BETWEEN(T0.""DocDueDate"", NOW()) AS ""Days"", -1 ");
            sb.AppendLine($@"                          FROM      {DBIQ}.ORPC T0 ");
            sb.AppendLine($@"                                    INNER JOIN {DBIQ}.OCRD T2 ON T2.""CardCode"" = T0.""CardCode"" ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBIQ}.CRD1 T4 ON T4.""CardCode"" = T0.""CardCode"" AND  T4.""AdresType"" = 'B' AND  ( T4.""LineNum"" = 0 OR   T4.""LineNum"" = 1 ) ");
            sb.AppendLine($@"                          WHERE     T0.""DocSubType"" = '--' AND T0.""DocStatus"" = 'O' AND ( T0.""CardCode"" LIKE 'B%' OR T0.""CardCode"" LIKE 'M%' ) ");
            sb.AppendLine($@"                          GROUP BY  T0.""DocNum"", T0.""DocDate"", T0.""DocDueDate"", T0.""CardCode"", T0.""CardName"", T0.""NumAtCard"", T0.""DocTotal"" ");
            sb.AppendLine($@"                                    , (( -T0.""DocTotal"" + T0.""PaidToDate"" ) * -1 ), DAYS_BETWEEN(T0.""DocDueDate"", NOW()) ) AS TA ");
            sb.AppendLine($@"                        INNER JOIN {DBIQ}.OSLP TB ON TB.""SlpCode"" = TA.""SlpCode"" ");
            sb.AppendLine($@"              UNION ");
            sb.AppendLine($@"              SELECT    'Miami', TA.""Type"", TA.""DocNum"", TA.""CardCode"", TA.""CardName"", ( CASE WHEN TA.""Type"" = 'Factura' THEN TA.""DocNum"" END ), TA.""DocBase"", TA.""DocDate"", TA.""Terms"", TA.""DocDueDate"" ");
            sb.AppendLine($@"                    , TA.""DocTotal"", TA.""Balance"", TA.""Days"" ");
            sb.AppendLine($@"                        , ( CASE WHEN ( TA.""Type"" = 'Factura' AND TA.""Days"" <= 0 ) THEN 'Vigente' ");
            sb.AppendLine($@"                                WHEN ( TA.""Type"" = 'Factura' AND TA.""Days"" > 0 ) THEN 'En  Mora' ");
            sb.AppendLine($@"                                WHEN ( TA.""Type"" = 'Pago Efectuado' ) THEN 'Abono' END ), TA.""BillNumber"", tb.""Memo"", tb.""SlpName"" ");
            sb.AppendLine($@"              FROM      ( SELECT    'Factura' AS ""Type"", T0.""CardCode"", T3.""CardName"", T0.""DocNum"", T1.""BaseRef"" AS ""DocBase"", T0.""NumAtCard"" AS ""BillNumber"", CAST(T0.""DocDate"" AS DATE) AS ""DocDate"" ");
            sb.AppendLine($@"                                    , T2.""PymntGroup"" AS ""Terms"", CAST(T0.""DocDueDate"" AS DATE) AS ""DocDueDate"", T0.""DocTotal"" * -1 AS ""DocTotal"" ");
            sb.AppendLine($@"                                    , (( T0.""DocTotal"" - T0.""PaidToDate"" ) * -1 ) AS ""Balance"", DAYS_BETWEEN(T0.""DocDueDate"", NOW()) AS ""Days"", T0.""SlpCode"" ");
            sb.AppendLine($@"                          FROM      {DBLA}.OPCH T0 ");
            sb.AppendLine($@"                                    INNER JOIN {DBLA}.PCH1 T1 ON T1.""DocEntry"" = T0.""DocEntry"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBLA}.OCTG T2 ON T0.""GroupNum"" = T2.""GroupNum"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBLA}.OCRD T3 ON T3.""CardCode"" = T0.""CardCode"" ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBLA}.CRD1 T4 ON T4.""CardCode"" = T0.""CardCode"" AND T4.""AdresType"" = 'B' AND ( T4.""LineNum"" = 0 OR   T4.""LineNum"" = 1 ) ");
            sb.AppendLine($@"                          WHERE     (( T0.""DocTotal"" - T0.""PaidToDate"" ) * -1 ) <> 0 AND T0.""DocSubType"" = '--' AND ( T0.""CardCode"" LIKE 'B%' OR T0.""CardCode"" LIKE 'M%' ) ");
            sb.AppendLine($@"                          GROUP BY  T0.""DocNum"", T0.""CardCode"", T0.""SlpCode"", T3.""CardName"", T1.""BaseRef"", T0.""DocDate"", T0.""DocDueDate"", T0.""DocTotal"", T2.""PymntGroup"", T0.""NumAtCard"" ");
            sb.AppendLine($@"                                , (( T0.""DocTotal"" - T0.""PaidToDate"" ) * -1 ) ");
            sb.AppendLine($@"                          UNION ");
            sb.AppendLine($@"                          SELECT    'Nota de Debito', T0.""CardCode"", T0.""CardName"", T0.""DocNum"", T1.""BaseRef"", T0.""NumAtCard"", CAST(T0.""DocDate"" AS DATE), T2.""PymntGroup"", CAST(T0.""DocDueDate"" AS DATE) ");
            sb.AppendLine($@"                                , T0.""DocTotal"", (( T0.""DocTotal"" - T0.""PaidToDate"" ) * -1 ), DAYS_BETWEEN(T0.""DocDueDate"", NOW()), T0.""SlpCode"" ");
            sb.AppendLine($@"                          FROM      {DBLA}.OPCH T0 ");
            sb.AppendLine($@"                                    INNER JOIN {DBLA}.PCH1 T1 ON T1.""DocEntry"" = T0.""DocEntry"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBLA}.OCTG T2 ON T0.""GroupNum"" = T2.""GroupNum"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBLA}.OCRD T3 ON T3.""CardCode"" = T0.""CardCode"" ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBLA}.CRD1 T4 ON T4.""CardCode"" = T0.""CardCode"" AND T4.""AdresType"" = 'B' AND ( T4.""LineNum"" = 0 OR T4.""LineNum"" = 1 ) ");
            sb.AppendLine($@"                          WHERE     T0.CANCELED = 'N' AND T0.""DocSubType"" = 'DM' AND ( T0.""DocTotal"" - T0.""PaidToDate"" ) * -1 <> 0 AND ( T0.""CardCode"" LIKE 'B%' OR T0.""CardCode"" LIKE 'M%' ) ");
            sb.AppendLine($@"                          GROUP BY  T0.""DocNum"", T0.""CardName"", T0.""SlpCode"", T1.""BaseRef"", T0.""DocDate"", T0.""DocDueDate"", T0.""DocTotal"", DAYS_BETWEEN(T0.""DocDueDate"", NOW()), T0.""CardCode"" ");
            sb.AppendLine($@"                                , T2.""PymntGroup"", T0.""NumAtCard"", ( T0.""DocTotal"" - T0.""PaidToDate"" ) ");
            sb.AppendLine($@"                          UNION ");
            sb.AppendLine($@"                          SELECT    'Pago Recibido', T0.""CardCode"", T0.""CardName"", T0.""DocNum"", '', '', CAST(T0.""DocDate"" AS DATE), '', CAST(T0.""DocDueDate"" AS DATE), T0.""DocTotal"" * -1, T0.""OpenBal"" * -1 ");
            sb.AppendLine($@"                                , DAYS_BETWEEN(T0.""DocDueDate"", NOW()), -1 ");
            sb.AppendLine($@"                          FROM      {DBLA}.ORCT T0 ");
            sb.AppendLine($@"                                    INNER JOIN {DBLA}.JDT1 T1 ON T0.""TransId"" = T1.""TransId"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBLA}.OCRD T2 ON T2.""CardCode"" = T0.""CardCode"" ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBLA}.CRD1 T4 ON T4.""CardCode"" = T0.""CardCode"" AND T4.""AdresType"" = 'B' AND ( T4.""LineNum"" = 0 OR   T4.""LineNum"" = 1 ) ");
            sb.AppendLine($@"                          WHERE     T0.""PayNoDoc"" = 'Y' AND T0.""Canceled"" = 'N' AND T0.""DocType"" = 'S' AND T0.""Canceled"" = 'N' AND T1.""ShortName"" = T0.""CardCode"" AND T1.""IntrnMatch"" = 0 ");
            sb.AppendLine($@"                                    AND ( T0.""CardCode"" LIKE 'B%' OR T0.""CardCode"" LIKE 'M%' ) ");
            sb.AppendLine($@"                          UNION ");
            sb.AppendLine($@"                          SELECT    'Pago Efectuado', T0.""CardCode"", T0.""CardName"", T0.""DocNum"", '', '', CAST(T0.""DocDate"" AS DATE), '', CAST(T0.""DocDueDate"" AS DATE), T0.""DocTotal"", T0.""OpenBal"" ");
            sb.AppendLine($@"                                , DAYS_BETWEEN(T0.""DocDueDate"", NOW()), -1 ");
            sb.AppendLine($@"                          FROM      {DBLA}.OVPM T0 ");
            sb.AppendLine($@"                                    INNER JOIN {DBLA}.OCRD T1 ON T0.""CardCode"" = T1.""CardCode"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBLA}.JDT1 T2 ON T0.""TransId"" = T2.""TransId"" ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBLA}.CRD1 T4 ON T4.""CardCode"" = T0.""CardCode"" AND T4.""AdresType"" = 'B' AND ( T4.""LineNum"" = 0 OR   T4.""LineNum"" = 1 ) ");
            sb.AppendLine($@"                          WHERE     T0.""PayNoDoc"" = 'Y' AND T0.""Canceled"" = 'N' AND T1.""CardType"" = 'S' AND T2.""ShortName"" = T0.""CardCode"" AND T2.""IntrnMatch"" = 0 AND T0.""OpenBal"" > 0 ");
            sb.AppendLine($@"                                    AND ( T0.""CardCode"" LIKE 'B%' OR T0.""CardCode"" LIKE 'M%' ) ");
            sb.AppendLine($@"                          UNION ");
            sb.AppendLine($@"                          SELECT    'Registro Diario', T2.""CardCode"", T2.""CardName"", T0.""TransId"", '', '', CAST(T0.""RefDate"" AS DATE) ");
            sb.AppendLine($@"                                    , T3.""PymntGroup"", CAST(T1.""DueDate"" AS DATE), 0, (( T1.""Credit"" - T1.""Debit"" ) * -1 ) AS ""Balance"", DAYS_BETWEEN(T1.""DueDate"", NOW()) AS ""Days"", -1 ");
            sb.AppendLine($@"                          FROM      {DBLA}.OJDT T0 ");
            sb.AppendLine($@"                                    INNER JOIN {DBLA}.JDT1 T1 ON T0.""TransId"" = T1.""TransId"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBLA}.OCRD T2 ON T1.""ShortName"" = T2.""CardCode"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBLA}.OCTG T3 ON T3.""GroupNum"" = T2.""GroupNum"" ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBLA}.CRD1 T4 ON T4.""CardCode"" = T2.""CardCode"" AND T4.""AdresType"" = 'B' AND ( T4.""LineNum"" = 0 OR   T4.""LineNum"" = 1 ) ");
            sb.AppendLine($@"                          WHERE     T1.""Account"" <> T1.""ShortName"" AND T0.""TransType"" = '30' AND T1.""IntrnMatch"" = 0 AND T2.""CardType"" = 'S' AND (( T1.""Credit"" - T1.""Debit"" ) * -1 ) <> 0 ");
            sb.AppendLine($@"                                    AND T1.""MthDate"" = '' AND ( T2.""CardCode"" LIKE 'B%' OR T2.""CardCode"" LIKE 'M%' ) ");
            sb.AppendLine($@"                          UNION ");
            sb.AppendLine($@"                          SELECT    'Nota de Credito', T0.""CardCode"", T0.""CardName"", T0.""DocNum"", '', T0.""NumAtCard"", CAST(T0.""DocDate"" AS DATE), '', CAST(T0.""DocDueDate"" AS DATE), T0.""DocTotal"" ");
            sb.AppendLine($@"                                , (( -T0.""DocTotal"" + T0.""PaidToDate"" ) * -1 ), DAYS_BETWEEN(T0.""DocDueDate"", NOW()), -1 ");
            sb.AppendLine($@"                          FROM      {DBLA}.ORPC T0 ");
            sb.AppendLine($@"                                    INNER JOIN {DBLA}.OCRD T2 ON T2.""CardCode"" = T0.""CardCode"" ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBLA}.CRD1 T4 ON T4.""CardCode"" = T0.""CardCode"" AND T4.""AdresType"" = 'B' AND ( T4.""LineNum"" = 0 OR   T4.""LineNum"" = 1 ) ");
            sb.AppendLine($@"                          WHERE     T0.""DocSubType"" = '--' AND T0.""DocStatus"" = 'O' AND ( T0.""CardCode"" LIKE 'B%' OR T0.""CardCode"" LIKE 'M%' ) ");
            sb.AppendLine($@"                          GROUP BY  T0.""DocNum"", T0.""DocDate"", T0.""DocDueDate"", T0.""CardCode"", T0.""CardName"", T0.""NumAtCard"", T0.""DocTotal"" ");
            sb.AppendLine($@"                                    , (( -T0.""DocTotal"" + T0.""PaidToDate"" ) * -1 ), DAYS_BETWEEN(T0.""DocDueDate"", NOW()) ) AS TA ");
            sb.AppendLine($@"                        INNER JOIN {DBLA}.OSLP TB ON TB.""SlpCode"" = TA.""SlpCode"" ");
            sb.AppendLine($@"              UNION ");
            sb.AppendLine($@"              SELECT    'Santa Cruz', TA.""Type"", TA.""DocNum"", TA.""CardCode"", TA.""CardName"", ( CASE WHEN TA.""Type"" = 'Factura' THEN TA.""DocNum"" END ) ");
            sb.AppendLine($@"                        , TA.""DocBase"", TA.""DocDate"", TA.""Terms"", TA.""DocDueDate"", TA.""DocTotal"", TA.""Balance"", TA.""Days"" ");
            sb.AppendLine($@"                        , ( CASE WHEN ( TA.""Type"" = 'Factura' AND  TA.""Days"" <= 0 ) THEN 'Vigente' ");
            sb.AppendLine($@"                                WHEN ( TA.""Type"" = 'Factura' AND   TA.""Days"" > 0 ) THEN 'En  Mora' ");
            sb.AppendLine($@"                                WHEN ( TA.""Type"" = 'Pago Efectuado' ) THEN 'Abono' END ), TA.""BillNumber"", tb.""Memo"", tb.""SlpName"" ");
            sb.AppendLine($@"              FROM      ( SELECT    'Factura' AS ""Type"", T0.""CardCode"", T3.""CardName"", T0.""DocNum"", T1.""BaseRef"" AS ""DocBase"", T0.""NumAtCard"" AS ""BillNumber"", CAST(T0.""DocDate"" AS DATE) AS ""DocDate"" ");
            sb.AppendLine($@"                                    , T2.""PymntGroup"" AS ""Terms"", CAST(T0.""DocDueDate"" AS DATE) AS ""DocDueDate"", T0.""DocTotal"" * -1 AS ""DocTotal"" ");
            sb.AppendLine($@"                                    , (( T0.""DocTotal"" - T0.""PaidToDate"" ) * -1 ) AS ""Balance"", DAYS_BETWEEN(T0.""DocDueDate"", NOW()) AS ""Days"", T0.""SlpCode"" ");
            sb.AppendLine($@"                          FROM      {DBSA}.OPCH T0 ");
            sb.AppendLine($@"                                    INNER JOIN {DBSA}.PCH1 T1 ON T1.""DocEntry"" = T0.""DocEntry"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBSA}.OCTG T2 ON T0.""GroupNum"" = T2.""GroupNum"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBSA}.OCRD T3 ON T3.""CardCode"" = T0.""CardCode"" ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBSA}.CRD1 T4 ON T4.""CardCode"" = T0.""CardCode"" AND T4.""AdresType"" = 'B' AND ( T4.""LineNum"" = 0 OR   T4.""LineNum"" = 1 ) ");
            sb.AppendLine($@"                          WHERE     (( T0.""DocTotal"" - T0.""PaidToDate"" ) * -1 ) <> 0 AND T0.""DocSubType"" = '--' AND ( T0.""CardCode"" LIKE 'B%' OR T0.""CardCode"" LIKE 'M%' ) ");
            sb.AppendLine($@"                          GROUP BY  T0.""DocNum"", T0.""CardCode"", T0.""SlpCode"", T3.""CardName"", T1.""BaseRef"", T0.""DocDate"", T0.""DocDueDate"", T0.""DocTotal"" ");
            sb.AppendLine($@"                                    , T2.""PymntGroup"", T0.""NumAtCard"", (( T0.""DocTotal"" - T0.""PaidToDate"" ) * -1 ) ");
            sb.AppendLine($@"                          UNION ");
            sb.AppendLine($@"                          SELECT    'Nota de Debito', T0.""CardCode"", T0.""CardName"", T0.""DocNum"", T1.""BaseRef"", T0.""NumAtCard"", CAST(T0.""DocDate"" AS DATE), T2.""PymntGroup"", CAST(T0.""DocDueDate"" AS DATE) ");
            sb.AppendLine($@"                                , T0.""DocTotal"", (( T0.""DocTotal"" - T0.""PaidToDate"" ) * -1 ), DAYS_BETWEEN(T0.""DocDueDate"", NOW()), T0.""SlpCode"" ");
            sb.AppendLine($@"                          FROM      {DBSA}.OPCH T0 ");
            sb.AppendLine($@"                                    INNER JOIN {DBSA}.PCH1 T1 ON T1.""DocEntry"" = T0.""DocEntry"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBSA}.OCTG T2 ON T0.""GroupNum"" = T2.""GroupNum"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBSA}.OCRD T3 ON T3.""CardCode"" = T0.""CardCode"" ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBSA}.CRD1 T4 ON T4.""CardCode"" = T0.""CardCode"" AND   T4.""AdresType"" = 'B' AND ( T4.""LineNum"" = 0 OR   T4.""LineNum"" = 1 ) ");
            sb.AppendLine($@"                          WHERE     T0.CANCELED = 'N' AND T0.""DocSubType"" = 'DM' AND ( T0.""DocTotal"" - T0.""PaidToDate"" ) * -1 <> 0 AND ( T0.""CardCode"" LIKE 'B%' OR T0.""CardCode"" LIKE 'M%' ) ");
            sb.AppendLine($@"                          GROUP BY  T0.""DocNum"", T0.""CardName"", T0.""SlpCode"", T1.""BaseRef"", T0.""DocDate"", T0.""DocDueDate"", T0.""DocTotal"" ");
            sb.AppendLine($@"                                    , DAYS_BETWEEN(T0.""DocDueDate"", NOW()), T0.""CardCode"", T2.""PymntGroup"", T0.""NumAtCard"", ( T0.""DocTotal"" - T0.""PaidToDate"" ) ");
            sb.AppendLine($@"                          UNION ");
            sb.AppendLine($@"                          SELECT    'Pago Recibido', T0.""CardCode"", T0.""CardName"", T0.""DocNum"", '', '', CAST(T0.""DocDate"" AS DATE), '' ");
            sb.AppendLine($@"                                    , CAST(T0.""DocDueDate"" AS DATE), T0.""DocTotal"" * -1, T0.""OpenBal"" * -1, DAYS_BETWEEN(T0.""DocDueDate"", NOW()), -1 ");
            sb.AppendLine($@"                          FROM      {DBSA}.ORCT T0 ");
            sb.AppendLine($@"                                    INNER JOIN {DBSA}.JDT1 T1 ON T0.""TransId"" = T1.""TransId"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBSA}.OCRD T2 ON T2.""CardCode"" = T0.""CardCode"" ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBSA}.CRD1 T4 ON T4.""CardCode"" = T0.""CardCode"" AND T4.""AdresType"" = 'B' AND ( T4.""LineNum"" = 0 OR   T4.""LineNum"" = 1 ) ");
            sb.AppendLine($@"                          WHERE     T0.""PayNoDoc"" = 'Y' AND T0.""Canceled"" = 'N' AND T0.""DocType"" = 'S' AND T0.""Canceled"" = 'N' AND T1.""ShortName"" = T0.""CardCode"" AND T1.""IntrnMatch"" = 0 ");
            sb.AppendLine($@"                                    AND ( T0.""CardCode"" LIKE 'B%' OR T0.""CardCode"" LIKE 'M%' ) ");
            sb.AppendLine($@"                          UNION ");
            sb.AppendLine($@"                          SELECT    'Pago Efectuado', T0.""CardCode"", T0.""CardName"", T0.""DocNum"", '', '', CAST(T0.""DocDate"" AS DATE), '' ");
            sb.AppendLine($@"                                    , CAST(T0.""DocDueDate"" AS DATE), T0.""DocTotal"", T0.""OpenBal"", DAYS_BETWEEN(T0.""DocDueDate"", NOW()) AS ""Days"", -1 ");
            sb.AppendLine($@"                          FROM      {DBSA}.OVPM T0 ");
            sb.AppendLine($@"                                    INNER JOIN {DBSA}.OCRD T1 ON T0.""CardCode"" = T1.""CardCode"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBSA}.JDT1 T2 ON T0.""TransId"" = T2.""TransId"" ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBSA}.CRD1 T4 ON T4.""CardCode"" = T0.""CardCode"" AND   T4.""AdresType"" = 'B' AND ( T4.""LineNum"" = 0 OR   T4.""LineNum"" = 1 ) ");
            sb.AppendLine($@"                          WHERE     T0.""PayNoDoc"" = 'Y' AND T0.""Canceled"" = 'N' AND T1.""CardType"" = 'S' AND T2.""ShortName"" = T0.""CardCode"" AND T2.""IntrnMatch"" = 0 AND T0.""OpenBal"" > 0 ");
            sb.AppendLine($@"                                    AND ( T0.""CardCode"" LIKE 'B%' OR T0.""CardCode"" LIKE 'M%' ) ");
            sb.AppendLine($@"                          UNION ");
            sb.AppendLine($@"                          SELECT    'Registro Diario', T2.""CardCode"", T2.""CardName"", T0.""TransId"", '', '', CAST(T0.""RefDate"" AS DATE) ");
            sb.AppendLine($@"                                    , T3.""PymntGroup"", CAST(T1.""DueDate"" AS DATE), 0, (( T1.""Credit"" - T1.""Debit"" ) * -1 ), DAYS_BETWEEN(T1.""DueDate"", NOW()), -1 ");
            sb.AppendLine($@"                          FROM      {DBSA}.OJDT T0 ");
            sb.AppendLine($@"                                    INNER JOIN {DBSA}.JDT1 T1 ON T0.""TransId"" = T1.""TransId"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBSA}.OCRD T2 ON T1.""ShortName"" = T2.""CardCode"" ");
            sb.AppendLine($@"                                    INNER JOIN {DBSA}.OCTG T3 ON T3.""GroupNum"" = T2.""GroupNum"" ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBSA}.CRD1 T4 ON T4.""CardCode"" = T2.""CardCode"" AND T4.""AdresType"" = 'B' AND ( T4.""LineNum"" = 0 OR   T4.""LineNum"" = 1 ) ");
            sb.AppendLine($@"                          WHERE     T1.""Account"" <> T1.""ShortName"" AND T0.""TransType"" = '30' AND T1.""IntrnMatch"" = 0 AND T2.""CardType"" = 'S' AND (( T1.""Credit"" - T1.""Debit"" ) * -1 ) <> 0 ");
            sb.AppendLine($@"                                    AND T1.""MthDate"" = '' AND ( T2.""CardCode"" LIKE 'B%' OR T2.""CardCode"" LIKE 'M%' ) ");
            sb.AppendLine($@"                          UNION ");
            sb.AppendLine($@"                          SELECT    'Nota de Credito', T0.""CardCode"", T0.""CardName"", T0.""DocNum"", '', T0.""NumAtCard"", CAST(T0.""DocDate"" AS DATE), '' ");
            sb.AppendLine($@"                                    , CAST(T0.""DocDueDate"" AS DATE), T0.""DocTotal"", (( -T0.""DocTotal"" + T0.""PaidToDate"" ) * -1 ), DAYS_BETWEEN(T0.""DocDueDate"", NOW()) AS ""Days"", -1 ");
            sb.AppendLine($@"                          FROM      {DBSA}.ORPC T0 ");
            sb.AppendLine($@"                                    INNER JOIN {DBSA}.OCRD T2 ON T2.""CardCode"" = T0.""CardCode"" ");
            sb.AppendLine($@"                                    LEFT OUTER JOIN {DBSA}.CRD1 T4 ON T4.""CardCode"" = T0.""CardCode"" AND   T4.""AdresType"" = 'B' AND ( T4.""LineNum"" = 0 OR   T4.""LineNum"" = 1 ) ");
            sb.AppendLine($@"                          WHERE     T0.""DocSubType"" = '--' AND T0.""DocStatus"" = 'O' AND ( T0.""CardCode"" LIKE 'B%' OR T0.""CardCode"" LIKE 'M%' ) ");
            sb.AppendLine($@"                          GROUP BY  T0.""DocNum"", T0.""DocDate"", T0.""DocDueDate"", T0.""CardCode"", T0.""CardName"", T0.""NumAtCard"", T0.""DocTotal"" ");
            sb.AppendLine($@"                                    , (( -T0.""DocTotal"" + T0.""PaidToDate"" ) * -1 ), DAYS_BETWEEN(T0.""DocDueDate"", NOW())) AS TA ");
            sb.AppendLine($@"                        INNER JOIN {DBSA}.OSLP TB ON TB.""SlpCode"" = TA.""SlpCode"" ) A ");
            sb.AppendLine($@"WHERE	{filter} ");
            sb.AppendLine($@"ORDER By {GetOrder(Order)}");

            IEnumerable<BEA.ProviderStateAccountItem> items = SQLList<BEA.ProviderStateAccountItem>(sb.ToString());
            return items;
        }

        #endregion

        #region Search Methods

        #endregion

        #region Constructors

        public StateAccount() : base() { }

        #endregion

    }
}
