//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQuoteReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsIquoteAPI.clsPendingRequest", Namespace="http://schemas.datacontract.org/2004/07/wsConsumer")]
    public partial class clsIquoteAPIclsPendingRequest : object
    {
        
        private string CountryCodeField;
        
        private string TaxRegionField;
        
        private string currencyField;
        
        private string[] distSkusField;
        
        private string hostAccountNumField;
        
        private int rqIdField;
        
        private string taxLocField;
        
        private string taxTypeField;
        
        private string typeOfSaleField;
        
        private string warehouseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxRegion
        {
            get
            {
                return this.TaxRegionField;
            }
            set
            {
                this.TaxRegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] distSkus
        {
            get
            {
                return this.distSkusField;
            }
            set
            {
                this.distSkusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hostAccountNum
        {
            get
            {
                return this.hostAccountNumField;
            }
            set
            {
                this.hostAccountNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rqId
        {
            get
            {
                return this.rqIdField;
            }
            set
            {
                this.rqIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string taxLoc
        {
            get
            {
                return this.taxLocField;
            }
            set
            {
                this.taxLocField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string taxType
        {
            get
            {
                return this.taxTypeField;
            }
            set
            {
                this.taxTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string typeOfSale
        {
            get
            {
                return this.typeOfSaleField;
            }
            set
            {
                this.typeOfSaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string warehouse
        {
            get
            {
                return this.warehouseField;
            }
            set
            {
                this.warehouseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsIquoteAPI.clsPnaItem", Namespace="http://schemas.datacontract.org/2004/07/wsConsumer")]
    public partial class clsIquoteAPIclsPnaItem : object
    {
        
        private string SKUField;
        
        private System.Nullable<float> discountedPriceField;
        
        private string messageField;
        
        private float priceField;
        
        private string statusField;
        
        private IQuoteReference.clsIquoteAPIclsShipment[] stockField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU
        {
            get
            {
                return this.SKUField;
            }
            set
            {
                this.SKUField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> discountedPrice
        {
            get
            {
                return this.discountedPriceField;
            }
            set
            {
                this.discountedPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IQuoteReference.clsIquoteAPIclsShipment[] stock
        {
            get
            {
                return this.stockField;
            }
            set
            {
                this.stockField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsIquoteAPI.clsShipment", Namespace="http://schemas.datacontract.org/2004/07/wsConsumer")]
    public partial class clsIquoteAPIclsShipment : object
    {
        
        private string NoteField;
        
        private System.DateTime arrivalField;
        
        private System.Nullable<decimal> discountedPriceField;
        
        private System.Nullable<decimal> priceField;
        
        private int quantityField;
        
        private string warehouseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note
        {
            get
            {
                return this.NoteField;
            }
            set
            {
                this.NoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime arrival
        {
            get
            {
                return this.arrivalField;
            }
            set
            {
                this.arrivalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> discountedPrice
        {
            get
            {
                return this.discountedPriceField;
            }
            set
            {
                this.discountedPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string warehouse
        {
            get
            {
                return this.warehouseField;
            }
            set
            {
                this.warehouseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsIquoteAPI.clsSkupair", Namespace="http://schemas.datacontract.org/2004/07/wsConsumer")]
    public partial class clsIquoteAPIclsSkupair : object
    {
        
        private string distSKUField;
        
        private string mfrSKUField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string distSKU
        {
            get
            {
                return this.distSKUField;
            }
            set
            {
                this.distSKUField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mfrSKU
        {
            get
            {
                return this.mfrSKUField;
            }
            set
            {
                this.mfrSKUField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsIquoteAPI.clsSKUprice", Namespace="http://schemas.datacontract.org/2004/07/wsConsumer")]
    public partial class clsIquoteAPIclsSKUprice : object
    {
        
        private string distSKUField;
        
        private decimal priceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string distSKU
        {
            get
            {
                return this.distSKUField;
            }
            set
            {
                this.distSKUField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IQuoteReference.I_iQuoteAPI")]
    public interface I_iQuoteAPI
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_iQuoteAPI/setPnaNotificationURL", ReplyAction="http://tempuri.org/I_iQuoteAPI/setPnaNotificationURLResponse")]
        System.Threading.Tasks.Task<string> setPnaNotificationURLAsync(string hostToken, string URL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_iQuoteAPI/getPendingPnaRequest", ReplyAction="http://tempuri.org/I_iQuoteAPI/getPendingPnaRequestResponse")]
        System.Threading.Tasks.Task<IQuoteReference.clsIquoteAPIclsPendingRequest> getPendingPnaRequestAsync(int rqId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_iQuoteAPI/listPendingPnaRequests", ReplyAction="http://tempuri.org/I_iQuoteAPI/listPendingPnaRequestsResponse")]
        System.Threading.Tasks.Task<int[]> listPendingPnaRequestsAsync(string hostToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_iQuoteAPI/sendPnaResponse", ReplyAction="http://tempuri.org/I_iQuoteAPI/sendPnaResponseResponse")]
        System.Threading.Tasks.Task<string> sendPnaResponseAsync(int rqId, IQuoteReference.clsIquoteAPIclsPnaItem[] entries);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_iQuoteAPI/listAvailableProducts", ReplyAction="http://tempuri.org/I_iQuoteAPI/listAvailableProductsResponse")]
        System.Threading.Tasks.Task<string[]> listAvailableProductsAsync(string hostToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_iQuoteAPI/addProducts", ReplyAction="http://tempuri.org/I_iQuoteAPI/addProductsResponse")]
        System.Threading.Tasks.Task<string> addProductsAsync(string hostToken, IQuoteReference.clsIquoteAPIclsSkupair[] entries);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_iQuoteAPI/removeProducts", ReplyAction="http://tempuri.org/I_iQuoteAPI/removeProductsResponse")]
        System.Threading.Tasks.Task<string> removeProductsAsync(string hostToken, string[] DistiSkus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_iQuoteAPI/setPrices", ReplyAction="http://tempuri.org/I_iQuoteAPI/setPricesResponse")]
        System.Threading.Tasks.Task<string> setPricesAsync(string hostToken, string priceBand, IQuoteReference.clsIquoteAPIclsSKUprice[] skuPrices);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_iQuoteAPI/restrictProducts", ReplyAction="http://tempuri.org/I_iQuoteAPI/restrictProductsResponse")]
        System.Threading.Tasks.Task<string> restrictProductsAsync(string hostToken, string[] distiskus, string[] customerIds);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface I_iQuoteAPIChannel : IQuoteReference.I_iQuoteAPI, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class I_iQuoteAPIClient : System.ServiceModel.ClientBase<IQuoteReference.I_iQuoteAPI>, IQuoteReference.I_iQuoteAPI
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public I_iQuoteAPIClient(EndpointConfiguration endpointConfiguration) : 
                base(I_iQuoteAPIClient.GetBindingForEndpoint(endpointConfiguration), I_iQuoteAPIClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public I_iQuoteAPIClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(I_iQuoteAPIClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public I_iQuoteAPIClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(I_iQuoteAPIClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public I_iQuoteAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> setPnaNotificationURLAsync(string hostToken, string URL)
        {
            return base.Channel.setPnaNotificationURLAsync(hostToken, URL);
        }
        
        public System.Threading.Tasks.Task<IQuoteReference.clsIquoteAPIclsPendingRequest> getPendingPnaRequestAsync(int rqId)
        {
            return base.Channel.getPendingPnaRequestAsync(rqId);
        }
        
        public System.Threading.Tasks.Task<int[]> listPendingPnaRequestsAsync(string hostToken)
        {
            return base.Channel.listPendingPnaRequestsAsync(hostToken);
        }
        
        public System.Threading.Tasks.Task<string> sendPnaResponseAsync(int rqId, IQuoteReference.clsIquoteAPIclsPnaItem[] entries)
        {
            return base.Channel.sendPnaResponseAsync(rqId, entries);
        }
        
        public System.Threading.Tasks.Task<string[]> listAvailableProductsAsync(string hostToken)
        {
            return base.Channel.listAvailableProductsAsync(hostToken);
        }
        
        public System.Threading.Tasks.Task<string> addProductsAsync(string hostToken, IQuoteReference.clsIquoteAPIclsSkupair[] entries)
        {
            return base.Channel.addProductsAsync(hostToken, entries);
        }
        
        public System.Threading.Tasks.Task<string> removeProductsAsync(string hostToken, string[] DistiSkus)
        {
            return base.Channel.removeProductsAsync(hostToken, DistiSkus);
        }
        
        public System.Threading.Tasks.Task<string> setPricesAsync(string hostToken, string priceBand, IQuoteReference.clsIquoteAPIclsSKUprice[] skuPrices)
        {
            return base.Channel.setPricesAsync(hostToken, priceBand, skuPrices);
        }
        
        public System.Threading.Tasks.Task<string> restrictProductsAsync(string hostToken, string[] distiskus, string[] customerIds)
        {
            return base.Channel.restrictProductsAsync(hostToken, distiskus, customerIds);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_I_iQuoteAPI))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_I_iQuoteAPI))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_I_iQuoteAPI))
            {
                return new System.ServiceModel.EndpointAddress("http://uat.channelcentral.net:8090/api/basic");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_I_iQuoteAPI))
            {
                return new System.ServiceModel.EndpointAddress("http://uat.channelcentral.net:8090/api/wsHttp");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_I_iQuoteAPI,
            
            WSHttpBinding_I_iQuoteAPI,
        }
    }
}
